### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Imel23** [xaldyz/dataflow-orbslam#1] opened 2020-02-07 21:35 UTC
Hello, 

I tried to run this code on a Jetson AGX Xavier, but i get this error:

`Thread 1 "mono_kitti" received signal SIGSEGV, Segmentation fault.
__memcpy_generic () at ../sysdeps/aarch64/multiarch/../memcpy.S:174
174	../sysdeps/aarch64/multiarch/../memcpy.S: No such file or directory.
`

Could you please help me, thank you in advance.

**Comment by xaldyz** [comment] 2020-02-17 13:12
Hello,
we ran the code without any issue on our Xavier, but I think I know where the problem could be.
Usually the segfault could be caused by the following missing lines in the configuration file, an example is located [here](https://github.com/xaldyz/dataflow-orbslam/blob/2429b96e1961d291fe40cb4c4bbcfa77bc7f11be/Examples/Monocular/KITTI04-12.yaml#L22) (actually, the config was wrong, so I updated it).

> `Camera.width: 1226`
> `Camera.height: 370`

where of course the two numbers represent width and height of the image.

Let me know if the insertion of these lines fixes your problem!
If not, please send the configuration of the compilation flags along with the sequence you are using

**Comment by xaldyz** [comment] 2020-02-24 10:01
I assume the problem is fixed by the tip. Feel free to re-open the issue if any help is needed (in case of SEGFAULT)

**Closed as completed by xaldyz** 2020-02-24 10:01 UTC
Labels: good first issue
